### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by onacrame** [square/pysurvival#2]
Will this work on Windows?

**Comment by MMindem** [comment]
I tried to install it it on windows using pip install, but compiling the c++ files fail due to the next error:
`   pysurvival/cpp_extensions/non_parametric.cpp(349): error C2065: 'M_PI': undeclared identifier
    pysurvival/cpp_extensions/non_parametric.cpp(364): error C2065: 'M_PI': undeclared identifier
    pysurvival/cpp_extensions/non_parametric.cpp(364): error C2065: 'M_PI': undeclared identifier
    error: command 'XX\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2` 

Seems that M_PI is not defined as discussed in [this](https://stackoverflow.com/questions/29264462/m-pi-not-available-with-gcc-std-c11-but-with-std-gnu11) and [this](https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier/26065595) topic on stackoverflow. 

Here I am using visual studio, but got the same error when compiling with MinGW. Furthermore I am using the latest anaconda distribution with python 3.7. 

Not sure whether this is only a bug or that the package will not work at all on windows.

**Comment by steph-likes-git** [comment]
Hi @MotoRZR and @MMindem,

Thanks so much for your interest in pysurvival. 
pysurvival isn't currently available on Windows, but I'm actively working on this. I will publish an update once it's ready.

Thanks for your interest in the project!

**Comment by ploner** [comment]
Hi @steph-likes-git,
is the package now available for Windows 10? I got a similar issue today w Py 3.8.9 as well as 3.9.10. 
Any idea how to fix it?
